// import { Inter } from 'next/font/google'
// import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

import "./globals.css";
import { Inter } from "next/font/google";

// import { switchThemeDuration } from "./constants";
import { ThemeProvider } from "./theme-provider";
import { ThemeSwitcher } from "./ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Whatsapp Web",
  description:
    "A simple app to showcase dark mode with Next.js and TailwindCSS",
  icons: {
    icon: "/whatsappIcon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/whatsappIcon.png" />
      </head>
      <body className={`${inter.className} bg-slate-50 dark:bg-[#b1b6a7] `}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ThemeSwitcher />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
